
# Set the working directory
WORKDIR /portfolio-app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the source code and other necessary files
COPY ./src ./src

# Copy tsconfig.json
COPY ./tsconfig.json ./

# Expose the port the app runs on (optional, depends on your app)
EXPOSE 3000

# Define the command to run the app (optional, depends on your app)
CMD ["npm", "run", "start"] 