# Enable Services like prometheus to watch pods
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: portfolio
  name: pod-reader
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-binding
  namespace: portfolio
subjects:
  - kind: ServiceAccount
    name: default
    namespace: portfolio
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
