apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-postgres-sc
  namespace: portfolio
  labels:
    app: backend-api
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
