FROM node:20 AS build
WORKDIR /app

RUN echo 'frontend'
ADD ./shared ./shared
RUN npm install --prefix ./shared
ADD ./frontend-web/package*.json ./
RUN npm install --legacy-peer-deps

ADD ./frontend-web .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]